# Generated by Django 6.0.3 on 2026-03-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='ticket_id',
        ),
        migrations.AddField(
            model_name='worklog',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
