# Generated by Django 6.0.3 on 2026-03-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_log', '0002_remove_worklog_ticket_id_worklog_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='ticket_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
