# Generated by Django 6.0.3 on 2026-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_log', '0003_worklog_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='worklog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('In Progress', 'In Progress')], max_length=20),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
